# This will automatically load a node version when it finds a .nvmrc file
# in the current working directory indicating which node version to load.
zstyle ':omz:plugins:nvm' autoload true

# Custom search engines
[[ -f ~/.search ]] && . ~/.search

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Powerlevel10k Prompt Customization.
# See https://github.com/Powerlevel9k/powerlevel9k#prompt-customization
source ~/.powerlevel10k

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  colored-man-pages
  fabric
  git
  kubectl
  npm
  nvm
  oc
  pyenv
  python
  rbenv
  web-search
  you-should-use
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Load the shell dotfiles.
for file in ~/.{exports,aliases_os,aliases,functions}; do
  [ -r "$file" ] && source "$file"
done
unset file

# Include local settings
[[ -f ~/.zshrc.local ]] && . ~/.zshrc.local
